### ISSUE TITLE
Change how we do releases

### ISSUE THREAD

**Issue by fho** [rtrlib/rtrlib#113]
I think we should the change the way how we do releases.
We haven't done a release since April but a lot of things changed. We don't have any clear guidelines for when to do releases.

Another approach would be that the master version is always the current releases and it's stability is guaranteed by the the travis tests.
As Minor Version Nr (?) we use automatically the latest git commit id in the Cmake file instead of incrementing it automatically.
The Changelog is removed instead we have meanigful short git commit descriptions and can use those as changelog or generate a CHANGELOG file from them automatically.

**Comment by waehlisch** [comment]
I don't like this approach. We should have explicit releases. My intention was to release a new version as soon as the new data structure is merged, And then start again with shorter cycles.
However, I agree it is a bit nontransparent which rules we follow for the version number.

**Comment by smlng** [comment]
I think we should have explicit releases, too. The feature set of RTRlib is rather fixed, most changes are bugfixes or (future) API enhancements, so no need for regular or rolling releases. We should make releases as a sufficient number of changes accumulated in the master since the last release or a major change is introduced.

For instance, after fixing the (big) validation bug, we should make the next official release and I suggest to release that one as version 1.0.0. Many people think of 0.x.y as some alpha or beta, hence pre-stable, version - IMHO RTRlib is beyond that phase ...

**Comment by fho** [comment]
Ok, it was only a spontaneous idea I had yesterday. :-)

It would be great if we could work out a guideline regarding releasing  and add it to the CONTRIBUTING doc.

> IMHO RTRlib is beyond that phase ...

Yes, should be after such a long time. On the other hand we had this major validation bug which made the library unusable.

Yes, I agree that people probably think version 0 means alpha version.
In general I would only increase the major number if the API becomes incompatible to the previous version.
I think it would be good to redesign the API and reimplement some parts and then release version 1.
