### ISSUE TITLE
Run CI builds with -Werror

### ISSUE THREAD

**Issue by nbars** [rtrlib/rtrlib#205]

**Comment by mroethke** [comment]
I'm not an overly big fan of -Werror, at least not the wildcard version, because its results are very specific to a compiler version.
Using either a newer or older version can lead to vastly different results.

And we have to clean up debug flags before we can enable this, there is a lot in there we obviously do not care about.

**Comment by nbars** [comment]
I agree that we should enable `-Werror` only for specific warnings.

**Comment by mroethke** [comment]
Right of off the top of my head two warnings that should be errors come to mind:

- incompatible-pointer-types
- implicit-function-declaration

Any further suggestions?
