### ISSUE TITLE
Extended rtrlclient to create multiple outputs

### ISSUE THREAD

**Issue by waehlisch** [rtrlib/rtrlib#219]
#### Background
Multiple implementations of RPKI origin validation (e.g., OpenBGPD) don't use RPKI RTR to maintain valid ROA data but import data from external files. Therefore, some RPKI validators provide a corresponding output which is then fed to the BGP router on a regular basis.

Such validator-centric approach is not good operational practice as it binds ROA output to a single Validator implementation and running instance. It would be better to benefit from the RPKI architecture, which allows a BGP router to receive data from multiple relying parties, e.g., to improve reliability.

#### Proposal (1)
The proposal is to extend the rtrclient such that it creates multiple output formats (see below) of the received valid ROA payload. It seems also helpful to introduce an option that terminates the rtrclient after receiving all data to make it easier to use in cron settings.

#### Proposal (2)
Preferably, we allow for easy extension of the output format, i.e., the user can configure how the output should look like. Typically, the required output consists of a fix preamble, dynamic content that includes the ROA, and a postamble.

For example, the OpenBGPD config:
```
roa-set { 
    203.119.88.0/23 maxlen 24 source-as 187
    2001:dd8:7::/48 maxlen 48 source-as 187        
    2401:680::/32 maxlen 32 source-as 715
}
deny quick from ebgp ovs invalid
```

A configuration file for this might look like
```
peamble:
  roa-set { 
content:
  $prefix/$length maxlen $maxlen source-as $origin
postamble:
  }
deny quick from ebgp ovs invalid
```

For a CSV file
```
  preamble:
    #this is a ROA CSV file
  content:
   $prefix,$length,$maxlen,$origin
  postamble:
```

### Useful links
https://rpki.readthedocs.io/en/latest/routinator/running.html#printing-a-list-of-valid-route-origins

**Comment by mroethke** [comment]
This seems out of scope for rtrclient, because what you want is to dump the state of the pfx table after the first sync. rtrclient just dumps the diff it applies to the table, that would not make much sense for the proposed use case especially when used with multiple caches.
This should be its own tool.

I would furthermore like to avoid implementing our own templating engine, there are more than enough out there already. [mustache](https://mustache.github.io/) [(c implementation)](https://gitlab.com/jobol/mustach) might be a candidate.

A script language might also be better suited for this than C.

**Comment by waehlisch** [comment]
I don't see that this is out of scope for the rtrclient. The rtrclient prints all received ROAs, the user can terminate the connection whenever he wants. It is not conflicting to have an extension that quits after the first sync was finished, in addition to the current live mode.

The question whether the rtrclient supports multiple caches or not is independent of the function above. Even in the current implementation, supporting multiple caches is valid.

Regarding the template engine: I agree that we should not start our own template engine. On the other, we learned in the past that users want lean implementations (with minimal dependencies to external libraries).

**Comment by mroethke** [comment]
On 2019-02-20 13:46:29, Matthias Wählisch wrote:
> I don't see that this is out of scope for the rtrclient. The rtrclient prints all received ROAs, the user can terminate the connection whenever he wants. It is not conflicting to have an extension that quits after the first sync was finished, in addition to the current live mode.

As I said, the use case is slightly different (dumping updates vs dumping
the populated pfx table), as long as only one cache is used that is
indeed not relevant but using multiple caches should not be an
afterthought here.

> The question whether the rtrclient supports multiple caches or not is independent of the function above. Even in the current implementation, supporting multiple caches is valid.

I disagree, because when using multiple caches the output would contain
duplicates.

>
> Regarding the template engine: I agree that we should not start our own template engine. On the other, we learned in the past that users want lean implementations (with minimal dependencies to external libraries).

The lib I mentioned is fairly small (400 LOC) and apache licensed,
vendoring would not be a problem.
