### ISSUE TITLE
RTRlib/ some delay when stopping a RPKI connection with FRR

### ISSUE THREAD

**Issue by pguibert6WIND** [rtrlib/rtrlib#254]
### Description
When using with FRR, BGP RPKI sometimes freezes with SSH configuration

### reproduction
I did it with [0]
with a RPKI configuration that we delete, and we recreate a new one. we can observe a 12 second delay between the calls to pthread_cancel() and pthread_join()
I do it with a ssh config, but I dont need any remote ssh server to do  that.

[0] https://github.com/FRRouting/frr/pull/5015

note: the problem happens when using 22 port, but not when using != 22 port.
### Expected results
```
Mar 03 15:24:02 bgpd[31859]: (2020/03/03 15:24:02:819582): RTR Socket: pthread_cancel()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:24:02:819600): RTR Socket: pthread_join()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:25:14:935700): SSH Transport(abcd@1.0.0.1:22): tr_ssh_init: opening SSH connection failed
```

### Actual results
```
Mar 03 15:24:02 bgpd[31859]: (2020/03/03 15:24:02:819582): RTR Socket: pthread_cancel()
Mar 03 15:24:02  bgpd[31859]: (2020/03/03 15:24:02:819600): RTR Socket: pthread_join()
Mar 03 15:25:14  bgpd[31859]: (2020/03/03 15:25:14:935700): SSH Transport(abcd@1.0.0.1:22): tr_ssh_init: opening SSH connection failed
```
### Analysis
it looks like in rtr.c file, we call `pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &oldcancelstate);` in the pthread created. then I guess the following calls will be kind of blocked.
```
rtr.c:          RTR_DBG1("pthread_cancel()");
rtr.c:          pthread_cancel(rtr_socket->thread_id);
rtr.c:          RTR_DBG1("pthread_join()");
rtr.c:          pthread_join(rtr_socket->thread_id, NULL);
```

**Comment by mroethke** [comment]
Cancelability is disabled because a thread must not be canceled while holding resources that are only locally reachable. I'll check if it can be enabled for the `tr_open` call.

**Comment by pguibert6WIND** [comment]
a test has been done to remove the call to `pthread_setcancelstate(PTHREAD_CANCEL_DISABLE`, and it solved the timeout issue.
no other tests have been done for that. may I trigger a pull request?

**Comment by mroethke** [comment]
No, that just leads to resource leaks.

**Comment by mroethke** [comment]
I don't think it can be made safe to enable cancelability for the connect calls. The tcp and ssh connect functions definitely hold local resources, while this could be fixed for tcp it cant be fixed for ssh because that is internal to libssh.
I will see if we can fix this in some other way.

**Comment by mroethke** [comment]
This is btw not limited to ssh, it also happens with tcp. I guess this is a side effect of switching from `pthread_kill` to `pthread_cancel`.

We could reduce the timeout, but that would not really fix the problem. We could also reintroduce a `pthread_kill` call, but we would also have to install a signal handler again. Which I would like to avoid, because a library should not modify process wide state.

I'm unsure how best to proceed.

**Comment by waehlisch** [comment]
How should we proceed @mroethke ? I'm not sure if I understand the problem completely.

**Comment by mroethke** [comment]
The problem is that some calls in the transport implementation are blocking. We handle most of them by setting cancelstate to ENABLE. But we can't do that for `tr_open` because it would cause memory leaks that we cannot fix. At least not for the ssh transport as they would occur in libssh.

We might be able to fix this by using non-blocking calls. But libssh does not support non-blocking calls for all relevant operations, we might be able to work around that though. But switching to non-blocking would not be trivial at all, I think.

However switching to non-blocking just for `tr_open` should be doable without to much effort, I think.

I will investigate both options.
